@startuml
component CommunicationContract
component CommunicationItem
component CoreValueResult
component DiagnosticSet
CommunicationContract --> CoreValueResult
CommunicationItem --> CommunicationContract
CommunicationItem --> CoreValueResult
CoreValueResult --> DiagnosticSet
@enduml
