@startuml
component ExtensionCatalog
component OwnershipGate
component OriginalGateSuite
component ExactCandidateRunner
OwnershipGate --> ExtensionCatalog
OriginalGateSuite --> OwnershipGate
ExactCandidateRunner --> OriginalGateSuite
@enduml
