@startuml
component DependencyManifest
component ToolchainProbe
component DiagnosticSet
component BuildEnvelope
DependencyManifest --> ToolchainProbe
ToolchainProbe --> DiagnosticSet
ToolchainProbe --> BuildEnvelope
@enduml
